const { features } = require("process")


const categories = ["electronics","headphones","wearables","audio"," home&kitchen","furniture","art","appliances","bathroom", "sports","football","basketball","tennis","baseball", "clothing","shirts","pants","shoes","accessories"]

const products =[{
  id: 1, 
  name:"Wireless Headphones" , 
  price:120, 
  image:"https://images.unsplash.com/photo-1657223144998-e5aa4fa2db7c?q=80&w=2730&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" , 
  category:["electronics", "audio"], 
  tag:["sale"],
  salesPrice: 99.99, 
  ratingCount: 42, 
  rating: 4.5, 
  description: "Experience crystal clear sound with our premium wireless headphones. Featuring active noise cancellation, 30-hour battery life, and comfortable over-ear design for all-day listening.", 
  features:["Active noise cancellation","Bluetooth 5.0 connectivity","30-hour battery life","Comfortable memory foam ear cushions","Built-in microphone for calls","Quick charging (3 hours playback from 15 minutes charge)"], 
  sku:"WH-100-BLK" , 
  stockStatus:"",
  quantity:12, 
  brand:"" , 
  color:["black", "white"] , 
  size:[]
}, 
{
  id:2, 
  name:"Smart Watch", 
  price:199.99,
  image:"https://images.unsplash.com/photo-1696688713460-de12ac76ebc6?q=80&w=2942&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", 
  category:["electronics", "wearables"],
  tag:[],
  salesPrice: , 
  ratingCount:28 , 
  rating:5 , 
  description: "Track your fitness, messages, and calls with a sleek, waterproof smartwatch that lasts all week.",
  features: ["Heart Rate Monitor", "Sleep Tracking", "Call Notifications", "Waterproof"],
  sku: "SW-200",
  stockStatus: "",
  quantity:20, 
  brand: "", 
  color: ["silver", "black"],
  size:[] 
},
{
  id:3, 
  name:"Bluetooth Speaker", 
  price:79.99,
  image:"https://images.unsplash.com/photo-1675319245480-215961c129f1?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", 
  category:["electronics", "audio"],
  tag:["new"],
  salesPrice: , 
  ratingCount:17 , 
  rating:4.5 , 
  description: "Portable waterproof Bluetooth speaker perfect for outdoor adventures and poolside parties.",
  features: ["360° Sound", "IPX7 Waterproof", "12-hour Playtime", "TWS Pairing"],
  sku: "BS-001",
  stockStatus: "",
  quantity:15, 
  brand: "", 
  color: ["blue", "black","white"], 
  size:[] 
},
{
  id:4, 
  name:"Laptop Bag", 
  price:49.99,
  image:"https://images.unsplash.com/photo-1622560481979-f5b0174242a0?q=80&w=2788&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", 
  category:["electronics", "accessories"],
  tag:[],
  salesPrice: , 
  ratingCount:35 , 
  rating: , 
  description: "Durable and stylish laptop bag with multiple compartments and padded interior.",
  features: ["Fits 15-inch laptops", "Water-resistant", "Adjustable shoulder strap"],
  sku: "LB-101",
  stockStatus:"" ,
  quantity:25, 
  brand: "", 
  color: ["gray", "black"],
  size:[] 
},
  {
    id: 5,
    name: "4K Monitor",
    price: 329.99,
    image: "https://images.unsplash.com/photo-1593642634367-d91a135587b5?q=80&w=2748&auto=format&fit=crop",
    category: ["electronics"],
    tag: [],
    salesPrice: ,
    ratingCount: 18,
    rating: 4.7,
    description: "Ultra HD 27-inch monitor with HDR support and USB-C connectivity.",
    features: ["4K Resolution", "HDR10", "USB-C", "Frameless design"],
    sku: "MON-4K-27",
    stockStatus: "",
    quantity: 6,
    brand: "",
    color: ["black"],
    size: []
  },
  {
    id: 6,
    name: "Gaming Mouse",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1587202372775-98907e86bba6?q=80&w=2780&auto=format&fit=crop",
    category: ["electronics", "accessories"],
    tag: ["gaming"],
    salesPrice: ,
    ratingCount: 95,
    rating: 4.8,
    description: "RGB gaming mouse with customizable buttons and ultra-responsive sensor.",
    features: ["RGB Lighting", "12K DPI Sensor", "Programmable Buttons"],
    sku: "GM-500X",
    stockStatus: "",
    quantity: 30,
    brand: "",
    color: ["black", "red"],
    size: []
  },
  {
    id: 7,
    name: "Portable Charger",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1612392061780-1c7c6629b9e0?q=80&w=2800&auto=format&fit=crop",
    category: ["electronics"],
    tag: [],
    salesPrice: ,
    ratingCount: 55,
    rating: 4.6,
    description: "10000mAh power bank with dual USB ports and LED battery display.",
    features: ["10000mAh", "Fast Charging", "Compact", "LED Display"],
    sku: "PB-100",
    stockStatus: "",
    quantity: 40,
    brand: "",
    color: ["white", "black"],
    size: []
  },
  {
    id: 8,
    name: "4K Smart TV",
    price: 699.99,
    image: "https://images.unsplash.com/photo-1600435335783-1038fe6a33f5",
    category: ["electronics", "home entertainment"],
    tag: ["sale"],
    salesPrice: ,
    ratingCount: 89,
    rating: 4.8,
    description: "55\" 4K UHD Smart TV with HDR",
    features: ["Smart OS", "Dolby Vision", "Voice Control"],
    sku: "TV-55UHD",
    stockStatus: "",
    quantity: 20,
    brand: "",
    color: ["black"],
    size: []
  },
  {
    id: 9,
    name: "Smart Home Hub",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?q=80&w=2780&auto=format&fit=crop",
    category: ["electronics", "home"],
    tag: [],
    salesPrice: ,
    ratingCount: 34,
    rating: 4.1,
    description: "Voice-activated smart hub that controls all your smart home devices in one place.",
    features: ["Voice Assistant", "Wi-Fi & Bluetooth", "App Integration"],
    sku: "HUB-360",
    stockStatus: "",
    quantity: 22,
    brand: "",
    color: ["white", "charcoal"],
    size: []
  },
  {
    id: 10,
    name: "Webcam 1080p",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1612832021071-f5cfaaf55708?q=80&w=2780&auto=format&fit=crop",
    category: ["electronics", "accessories"],
    tag: ["remote work"],
    salesPrice: ,
    ratingCount: 19,
    rating: 4.2,
    description: "Full HD webcam with built-in microphone, perfect for streaming and meetings.",
    features: ["1080p Video", "Built-in Microphone", "Plug & Play"],
    sku: "WC-HD1080",
    stockStatus: "",
    quantity: 16,
    brand: "",
    color: ["black"],
    size: []
  },
{
    id: 11,
    name: "Stainless Steel Cookware Set",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1583778176476-4a8b02d6a8b7",
    category: ["home & kitchen"],
    tag: [""],
    salesPrice: ,
    ratingCount: 45,
    rating: 4.7,
    description: "10-piece professional cookware set",
    features: ["Oven-safe", "Dishwasher safe"],
    sku: "CKV-10",
    stockStatus: "",
    quantity: 40,
    brand: "",
    color: ["silver"],
    size: []
  },
  {
    id: 12,
    name: "Vintage Bath Tub",
    price: 259.2,
    image: "https://images.unsplash.com/photo-1601042013937-4f2a77c9a9c7",
    category: ["home & kitchen"],
    tag: [""],
    salesPrice: ,
    ratingCount: 52,
    rating: 4.0,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 12.",
    features: ["Feature 1", "Feature 2", "Feature 3"],
    sku: "HO-012",
    stockStatus: "",
    quantity: 69,
    brand: "",
    color: ["black", "white"],
    size: [],
  },
  {
    id: 13,
    name: "Stand Mixer",
    price: 170.3,
    image: "https://images.unsplash.com/photo-1601042013937-4f2a77c9a9c7",
    category: ["home & kitchen"],
    tag: ["sale"],
    salesPrice:,
    ratingCount: 37,
    rating: 3.6,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 13.",
    features: ["Feature 1", "Feature 2"],
    sku: "HO-013",
    stockStatus: "",
    quantity: 9,
    brand: "",
    color: ["green", "red"],
    size: [],
  },
  {
    id: 14,
    name: "Home & Kitchen Item 14",
    price: 299.32,
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092",
    category: ["home & kitchen"],
    tag: ["featured"],
    salesPrice:,
    ratingCount: 74,
    rating: 5.0,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 14.",
    features: ["Feature 1", "Feature 2", "Feature 3"],
    sku: "HO-014",
    stockStatus: "",
    quantity: 93,
    brand: "",
    color: ["green"],
    size: [],
  },
  {
    id: 15,
    name: "Home & Kitchen Item 15",
    price: 253.83,
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092",
    category: ["home & kitchen"],
    tag: [""],
    salesPrice: ,
    ratingCount: 20,
    rating: 5.0,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 15.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "HO-015",
    stockStatus: "in_stock",
    quantity: 82,
    brand: "ComfortHaus",
    color: ["black"],
    size: [],
  },
  {
    id: 16,
    name: "Home & Kitchen Item 16",
    price: 165.77,
    image: "https://images.unsplash.com/photo-1601042013937-4f2a77c9a9c7",
    category: ["home & kitchen"],
    tag: [""],
    salesPrice: ,
    ratingCount: 65,
    rating: 4.0,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 16.",
    features: ["Feature 1", "Feature 2"],
    sku: "HO-016",
    stockStatus: "",
    quantity: 40,
    brand: "",
    color: ["red", "white"],
    size: [],
  },
  {
    id: 17,
    name: "Home & Kitchen Item 17",
    price: 228.08,
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092",
    category: ["home & kitchen"],
    tag: ["sale"],
    salesPrice: ,
    ratingCount: 85,
    rating: 4.5,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 17.",
    features: ["Feature 1", "Feature 2", "Feature 3"],
    sku: "HO-017",
    stockStatus: "",
    quantity: 24,
    brand: "",
    color: ["black"],
    size: [],
  },
  {
    id: 18,
    name: "Home & Kitchen Item 18",
    price: 149.23,
    image: "https://images.unsplash.com/photo-1601042013937-4f2a77c9a9c7",
    category: ["home & kitchen"],
    tag: ["featured"],
    salesPrice: ,
    ratingCount: 46,
    rating: 3.7,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 18.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4"],
    sku: "HO-018",
    stockStatus: "",
    quantity: 89,
    brand: "",
    color: ["red", "blue"],
    size: [],
  },
  {
    id: 19,
    name: "Home & Kitchen Item 19",
    price: 11.01,
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092",
    category: ["home & kitchen"],
    tag: [""],
    salesPrice: ,
    ratingCount: 94,
    rating: 4.3,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 19.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "HO-019",
    stockStatus: "",
    quantity: 63,
    brand: "",
    color: ["blue", "red"],
    size: [],
  },
  {
    id: 20,
    name: "Home & Kitchen Item 20",
    price: 202.23,
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092",
    category: ["home & kitchen"],
    tag: ["featured"],
    salesPrice: ,
    ratingCount: 99,
    rating: 4.5,
    description:
      "This is a high-quality home & kitchen item called Home & Kitchen Item 20.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "HO-020",
    stockStatus: "",
    quantity: 91,
    brand: "",
    color: ["blue", "white"],
    size: [],
  },
  {
    id: 21,
    name: "Sports Item 21",
    price: 110.56,
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 93,
    rating: 4.4,
    description: "This is a high-quality sports item called Sports Item 21.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "SP-021",
    stockStatus: "",
    quantity: 58,
    brand: "",
    color: ["blue"],
    size: [],
  },
  {
    id: 22,
    name: "Sports Item 22",
    price: 152.65,
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 76,
    rating: 4.1,
    description: "This is a high-quality sports item called Sports Item 22.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "SP-022",
    stockStatus: "",
    quantity: 90,
    brand: "",
    color: ["blue", "black"],
    size: [],
  },
  {
    id: 23,
    name: "Sports Item 23",
    price: 42.07,
    image: "https://images.unsplash.com/photo-1599050751761-7d92859f11c5",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 94,
    rating: 4.3,
    description: "This is a high-quality sports item called Sports Item 23.",
    features: ["Feature 1", "Feature 2", "Feature 3"],
    sku: "SP-023",
    stockStatus: "",
    quantity: 45,
    brand: "",
    color: ["green", "blue"],
    size: [],
  },
  {
    id: 24,
    name: "Sports Item 24",
    price: 256.37,
    image: "https://images.unsplash.com/photo-1592928309029-7a6cbd33218b",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 98,
    rating: 4.4,
    description: "This is a high-quality sports item called Sports Item 24.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4"],
    sku: "SP-024",
    stockStatus: "",
    quantity: 22,
    brand: "",
    color: ["black", "white"],
    size: [],
  },
  {
    id: 25,
    name: "Sports Item 25",
    price: 195.66,
    image: "https://images.unsplash.com/photo-1599050751761-7d92859f11c5",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 51,
    rating: 3.9,
    description: "This is a high-quality sports item called Sports Item 25.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "SP-025",
    stockStatus: "",
    quantity: 62,
    brand: "",
    color: ["blue"],
    size: [],
  },
  {
    id: 26,
    name: "Sports Item 26",
    price: 280.85,
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 54,
    rating: 4.9,
    description: "This is a high-quality sports item called Sports Item 26.",
    features: ["Feature 1", "Feature 2"],
    sku: "SP-026",
    stockStatus: "",
    quantity: 22,
    brand: "",
    color: ["white"],
    size: [],
  },
  {
    id: 27,
    name: "Sports Item 27",
    price: 238.6,
    image: "https://images.unsplash.com/photo-1599050751761-7d92859f11c5",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 73,
    rating: 4.2,
    description: "This is a high-quality sports item called Sports Item 27.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "SP-027",
    stockStatus: "",
    quantity: 47,
    brand: "",
    color: ["red"],
    size: [],
  },
  {
    id: 28,
    name: "Sports Item 28",
    price: 77.19,
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 27,
    rating: 3.8,
    description: "This is a high-quality sports item called Sports Item 28.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4"],
    sku: "SP-028",
    stockStatus: "",
    quantity: 14,
    brand: "",
    color: ["green", "red"],
    size: [],
  },
  {
    id: 29,
    name: "Sports Item 29",
    price: 272.59,
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 52,
    rating: 4.0,
    description: "This is a high-quality sports item called Sports Item 29.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4"],
    sku: "SP-029",
    stockStatus: "",
    quantity: 23,
    brand: "",
    color: ["red", "green"],
    size: [],
  },
  {
    id: 30,
    name: "Sports Item 30",
    price: 249.06,
    image: "https://images.unsplash.com/photo-1592928309029-7a6cbd33218b",
    category: ["sports"],
    tag: [""],
    salesPrice: ,
    ratingCount: 97,
    rating: 4.6,
    description: "This is a high-quality sports item called Sports Item 30.",
    features: ["Feature 1", "Feature 2", "Feature 3"],
    sku: "SP-030",
    stockStatus: "",
    quantity: 17,
    brand: "",
    color: ["green"],
    size: [],
  },
  {
    id: 31,
    name: "Clothing Item 31",
    price: 236.09,
    image: "https://images.unsplash.com/photo-1520975661595-6453be3f7070",
    category: ["clothing"],
    tag: [""],
    salesPrice: 211.48,
    ratingCount: 21,
    rating: 4.6,
    description:
      "This is a high-quality clothing item called Clothing Item 31.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "CL-031",
    stockStatus: "",
    quantity: 40,
    brand: "",
    color: ["black"],
    size: ["XL"],
  },
  {
    id: 32,
    name: "Clothing Item 32",
    price: 202.85,
    image: "https://images.unsplash.com/photo-1520975661595-6453be3f7070",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 39,
    rating: 4.3,
    description:
      "This is a high-quality clothing item called Clothing Item 32.",
    features: ["Feature 1", "Feature 2"],
    sku: "CL-032",
    stockStatus: "",
    quantity: 81,
    brand: "",
    color: ["red"],
    size: [],
  },
  {
    id: 33,
    name: "Clothing Item 33",
    price: 295.67,
    image: "https://images.unsplash.com/photo-1520975661595-6453be3f7070",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 89,
    rating: 3.8,
    description:
      "This is a high-quality clothing item called Clothing Item 33.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "CL-033",
    stockStatus: "",
    quantity: 22,
    brand: "",
    color: ["green"],
    size: [],
  },
  {
    id: 34,
    name: "Clothing Item 34",
    price: 36.5,
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 71,
    rating: 4.0,
    description:
      "This is a high-quality clothing item called Clothing Item 34.",
    features: ["Feature 1", "Feature 2"],
    sku: "CL-034",
    stockStatus: "",
    quantity: 73,
    brand: "",
    color: ["blue", "white"],
    size: ["XL", "L"],
  },
  {
    id: 35,
    name: "Clothing Item 35",
    price: 46.74,
    image: "https://images.unsplash.com/photo-1520975661595-6453be3f7070",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 38,
    rating: 4.6,
    description:
      "This is a high-quality clothing item called Clothing Item 35.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4"],
    sku: "CL-035",
    stockStatus: "",
    quantity: 27,
    brand: "",
    color: ["black", "blue"],
    size: [],
  },
  {
    id: 36,
    name: "Clothing Item 36",
    price: 138.01,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 50,
    rating: 4.1,
    description:
      "This is a high-quality clothing item called Clothing Item 36.",
    features: ["Feature 1", "Feature 2"],
    sku: "CL-036",
    stockStatus: "",
    quantity: 98,
    brand: "",
    color: ["white", "blue"],
    size: ["L", "S"],
  },
  {
    id: 37,
    name: "Clothing Item 37",
    price: 79.62,
    image: "https://images.unsplash.com/photo-1520975661595-6453be3f7070",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 90,
    rating: 4.1,
    description:
      "This is a high-quality clothing item called Clothing Item 37.",
    features: ["Feature 1", "Feature 2", "Feature 3"],
    sku: "CL-037",
    stockStatus: "",
    quantity: 96,
    brand: "",
    color: ["blue"],
    size: ["L"],
  },
  {
    id: 38,
    name: "Clothing Item 38",
    price: 176.75,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 73,
    rating: 4.8,
    description:
      "This is a high-quality clothing item called Clothing Item 38.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    sku: "CL-038",
    stockStatus: "",
    quantity: 19,
    brand: "",
    color: ["blue", "white"],
    size: ["XL", "M"],
  },
  {
    id: 39,
    name: "Clothing Item 39",
    price: 233.59,
    image: "https://images.unsplash.com/photo-1520975661595-6453be3f7070",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 92,
    rating: 4.5,
    description:
      "This is a high-quality clothing item called Clothing Item 39.",
    features: ["Feature 1", "Feature 2", "Feature 3", "Feature 4"],
    sku: "CL-039",
    stockStatus: "",
    quantity: 51,
    brand: "",
    color: ["green", "white"],
    size: [],
  },
  {
    id: 40,
    name: "Clothing Item 40",
    price: 276.6,
    image: "https://images.unsplash.com/photo-1520975661595-6453be3f7070",
    category: ["clothing"],
    tag: [""],
    salesPrice: ,
    ratingCount: 30,
    rating: 4.6,
    description:
      "This is a high-quality clothing item called Clothing Item 40.",
    features: ["Feature 1", "Feature 2", "Feature 3"],
    sku: "CL-040",
    stockStatus: "",
    quantity: 5,
    brand: "",
    color: ["green", "black"],
    size: ["L"],
  },
];

// {
//   id:, 
//   name:, 
//   price:,
//   image:"", 
//   category:[],
//   tag:[],
//   salesPrice: , 
//   ratingCount: , 
//   rating: , 
//   description: , 
//   features: [], 
//   sku: , 
//   stockStatus: ,
//   quantity: , 
//   brand: , 
//   color:[] , 
//   size:[] 
// },



